### ISSUE TITLE
Allow target database to be on a different machine from the one on which uploader script runs

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#133]
Right now the `linz_bde_uploader` command (or library?) requests a COPY from a file, effectively requiring that the PostgreSQL server is on the same system (or as access to the same filesystem) in which the uploader script is running.

This ticket is to enhance it to support uploading to a remote PostgreSQL server instead. This would be required, for example, to use a DaaS as the target for the upload.

REF: https://github.com/linz/bde-processor-deployment/issues/61

\cc @imincik

**Comment by strk** [comment]
Useful reference (I'm already working on this):
https://metacpan.org/pod/DBD::Pg#COPY-support

**Comment by strk** [comment]
Once this support is in place we might completely avoid writing to disk the temporary file too by implementing streamed bde_copy: https://github.com/linz/linz_bde_copy/issues/31

**Comment by palmerj** [comment]
> Once this support is in place we might completely avoid writing to disk the temporary file too by implementing streamed bde_copy: linz/linz_bde_copy#31

Yes this is a good idea.

**Comment by strk** [comment]
The streaming interface will need to be exported in the perl BDE library:
https://github.com/linz/linz_bde_perl/issues/23
