### ISSUE TITLE
[debian] Publish 2.4.0 package

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#150]
See https://github.com/linz/linz_bde_uploader/releases/tag/2.4.0

**Comment by imincik** [comment]
@strk , I am not sure which packages should be included in `Build-Depends`. With current `debian/control` file, I get following error during package build:

```
Checking prerequisites...
  requires:
    !  LINZ::Bde is not installed
    !  LINZ::Config is not installed
    !  Log::Dispatch is not installed
    !  Log::Dispatch::Email::MailSender is not installed
    !  Log::Dispatch::FileRotate is not installed
    !  Log::Log4perl is not installed
    !  Try::Tiny is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.
```

If I install everything which is in binary package `Depends` error will disappear. But is it correct to add all those packages as Build-Depends` ?

**Comment by strk** [comment]
Good question, I dunno what debian policy is in this reguard, but I guess those runtime dependencies are required for running tests, which are considered part of build ?

**Comment by strk** [comment]
I'd say just add to Build-Depends all it takes from Depends so this can move forward.

**Comment by imincik** [comment]
Thanks @strk

**Comment by imincik** [comment]
Package built and uploaded in `test`. Please move it to `prod` once tested.
