### ISSUE TITLE
Successful exit code when there's no dataset to upload ?

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#153]
I was hit by error exit code from `linz_bde_uploader` when the BDE repository directory is empty AND when no dataset exists before the date specified with `-before` switch. To me those occurrences are not to be considered errors but normal runs: there's nothing to upload, nothing to do, success!

What do you think @palmerj @imincik ?

**Comment by palmerj** [comment]
Do you mean no dataset sub-directories within the root BDE repository directory that meets the `-before` condition? If so, then it shouldn't be an error.

**Comment by imincik** [comment]
I agree with @palmerj

**Comment by strk** [comment]
On Mon, Feb 12, 2018 at 06:25:21PM +0000, Jeremy Palmer wrote:
> Do you mean no dataset sub-directories within the root BDE repository directory that meets the `-before` condition? If so, then it shouldn't be an error.

Yes, I mean that. No sub-directories meeting the `-b <before>`
condition results in a non-zero exit code from `linz-bde-uploader`.

Is @Ashleigh still around to add a test for this ?

**Comment by palmerj** [comment]
> Is @Ashleigh still around to add a test for this ?

She is here until the end of next week. If @billgeo agrees she might be able to fit it in after finishing off the bde documentation work.
