### ISSUE TITLE
Don't refuse to run in absence of level_0 when level_0 is not needed

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#155]
There are situations in which no `level_0` dataset is required for a run, but the uploader is refusing to run without any such `level_0`. See background here: https://github.com/linz/bde-processor-deployment/issues/272

The commandline is:
```
     linz_bde_uploader \
        -before ${BEFORE} \
        -full-incremental \
        -incremental \
        -config-path $CONFIG \
        -config-extension $CONFIG_EXT \
        -verbose \
        -log-level INFO \
        -remove-zombie
```

\cc @imincik @palmerj

**Comment by palmerj** [comment]
I would say if the `-full` or  `-full-incremental` switches are used then it's correct logic for the programme to try and find look for level 0 subfolders. Maybe we could just make https://github.com/linz/linz_bde_uploader/blob/master/lib/LINZ/BdeUpload.pm#L625 a warning instead?

**Comment by strk** [comment]
`try and find` is key here, isn't it ? It tried and not found any `level_0` dataset, is that an error ? I'm not even sure it should be a warning. Maybe we can tell something about which directories are mandatory and which not in https://github.com/linz/bde-processor-deployment/wiki/BDE-Store-Content-Specification (should that page be moved to public, btw ?)

**Comment by palmerj** [comment]
> try and find is key here, isn't it ? It tried and not found any level_0 dataset

That's because it's managed in https://github.com/linz/linz-bde-perl. When calls like $self->repository->level0 or $self->repository->level5 are made then it will look for the directories.

**Comment by strk** [comment]
On Wed, Jun 13, 2018 at 11:49:54AM +0000, Jeremy Palmer wrote:
> > try and find is key here, isn't it ? It tried and not found any level_0 dataset
> 
> That's because it's managed in https://github.com/linz/linz-bde-perl. When calls like $self->repository->level0 or $self->repository->level5 are made then it will look for the directories.

Yes, but is that to be considered a valid state, for
which an empty array can be returned, or does it need
to be an exceptional condition indicating a corrupted
store ?

**Comment by palmerj** [comment]
> Yes, but is that to be considered a valid state, for
which an empty array can be returned, or does it need
to be an exceptional condition indicating a corrupted
store ?

A valid repo should have at level the top level_0 and level_5 folders, but I don't think it should be a g requirements to have dataset sub directories. So $self->repository->level5 and $self->repository->level0 should continue to die if the directories are not folder. But I think it's safe to change linz_bde_uploader to just raise a warning, rather than an error if a empty array of datasets is returned.

**Comment by strk** [comment]
I think this can be considered closed via https://github.com/linz/linz_bde_uploader/pull/162
