### ISSUE TITLE
Improve full incremental to check that future updates are not applied. 

### ISSUE THREAD

**Issue by palmerj** [linz/linz_bde_uploader#20]
If apply_level0_inc is set from the command line, we need to check that future updates are already applied to the database. If this is the case the update should abort.

I suspect this should be fixed in BdeUpload::GetLevel0Updates after the $db->lastUploadStats call is made. But more investigation is required

**Comment by strk** [comment]
is this ticket still useful ?

**Comment by palmerj** [comment]
It's very old. We can close it and re-open if it really does cause future operational issues.
