### ISSUE TITLE
Add "GD49 coordinate order" to geodetic_marks

### ISSUE THREAD

**Issue by palmerj** [linz/linz_bde_uploader#21]
Add "GD49 coordinate order" column  to lds.geodetic_marks. Geodetic contractors have asked for this as part of annual upgrade works.

Prerequisite Issue #14

**Comment by palmerj** [comment]
Not sure if this is still valid. @ccrook: can you confirm with the team if users still want the gd49 order for their GIS needs? I know it's possible to get this via the GDB in any case.

**Comment by ccrook** [comment]
Will see what I can find out .. can't really imagine why anyone would want to know this now!

**Comment by ccrook** [comment]
Have confirmed with Nic and Jerry, this is no longer a requirement.
