### ISSUE TITLE
Background linz_bde_uploader process

### ISSUE THREAD

**Issue by palmerj** [linz/linz_bde_uploader#25]
Provide option to background task when run from the commandline

```
$ sudo linz_bde_uploader -b ...
```

or more simply

```
$ sudo run_bde_upload -b
```

Originally raised by @rcoup

**Comment by rcoup** [comment]
Further to this, the `sudo`/`at` combination causes issues wrt event hooks:

```
myuser ~ $ echo "/usr/bin/run_bde_upload -full-incremental -incremental" | sudo -u lds_bde at now
```

Ends up running the BDE upload (and event hooks) with `HOME=/home/myuser` instead of `HOME=/home/lds_bde`. So I think it should be `sudo -Hu` or `sudo -iu`.

**Comment by palmerj** [comment]
This now has in part been resolved by #35. Title of issue change to just background of process

**Comment by strk** [comment]
I guess the milestone assigned to this issue (Release 2.1) should be changed as the latest release was 2.3.0

**Comment by palmerj** [comment]
With changes coming in the NG of BDE Processor I think this feature is no longer required. Closing. Please reopen if you still think it's required
