### ISSUE TITLE
Add an index to the TA grid table for AIMS

### ISSUE THREAD

**Issue by billgeo** [linz/linz_bde_uploader#29]
additional index needed on territorial_authority_grid table

create index territorial_authority_grid_territorial_authority_ogc_fid_idx on admin_bdys.territorial_authority_grid(territorial_authority_ogc_fid);

linz/AIMS#60 (comment)

**Comment by palmerj** [comment]
Hey @billgeo should this not be an issue for the admin boundaries project?

**Comment by billgeo** [comment]
Yep. moved.
