### ISSUE TITLE
Merge changes from old BDE repo

### ISSUE THREAD

**Issue by billgeo** [linz/linz_bde_uploader#32]
See changes since this repo was created at https://github.com/linz/linz_bde_uploader_private/tree/release_1_5

**Comment by palmerj** [comment]
Hi Bill are you able to prepare a PR for the changes required here? Maybe none here only for the linz-lds-bde-schema and linz-bde-schema?

**Comment by billgeo** [comment]
Only changes here are altering the example configuration files.

**Comment by billgeo** [comment]
Will try and get to this next week.

**Comment by billgeo** [comment]
Pull request made
