### ISSUE TITLE
Possibility to override values in linz_bde_uploader.conf file

### ISSUE THREAD

**Issue by imincik** [linz/linz_bde_uploader#33]
Implement possibility to override some values in linz_bde_uploader.conf file with some other configuration file or directory of overriding files (/etc/linz-bde-uploader/conf.d).

This will help to maintain only small number of variables which differs from default, instead of maintaining and comparing whole big configuration files between every major releases.

NOTE:
There is "config-extension" option already included in inz_bde_uploader, but I am not sure if it can be used for this purpose.

**Comment by palmerj** [comment]
Can you please be clear why this is needed?

**Comment by imincik** [comment]
@palmerj , I have updated task to some better solution which I originally considered as more difficult to implement. But this is probably the best solution.

**Comment by palmerj** [comment]
You can already override parameters in *.conf.test file. Would that work? Maybe we can rename that file to something like * conf.override to make it clear what it is and can be used in production. I could also just go with you idea of conf.d/*.conf with a few more lines of code

**Comment by imincik** [comment]
".conf.test file" is not suitable name for production. On the other hand "conf.d" can be overkill. Maybe having ".conf.override" is just enough.

**Comment by palmerj** [comment]
Agreed it just simpler this way as there is also a tables.conf and linz_bde_uploader.conf. Also this method fits with the current LINZ:: Config perl module capabilities. 
How about testing this with the "-config-extension" or -"x" command line option set to 'override'?

If you are happy then the default of 'override' can be set here: 
https://github.com/linz/linz_bde_uploader/blob/master/bin/linz_bde_uploader.pl#L62

**Comment by imincik** [comment]
Does it means that we can solve whole problem with using "-config-extension" option ?
If yes, what is the correct value - "override", ".override", "conf.override" or ".conf.override" if I want to have "/etc/linz-bde-uploader/linz_bde_uploader.conf" as overriding file ?

**Comment by imincik** [comment]
@palmerj , I have some progress with using "-config-extension" option. I looks that it can solve the problem.

I was able to perform full upload
```
$ linz_bde_uploader
-full
-before 20150701
-config-path /tmp/test_bde_config_0de28ad6ed428bac5dd17788be23554a/linz_bde_uploader.conf -config-extension test_bde_0de28ad6ed428bac5dd17788be23554a
-verbose
-log-level WARN
```

but next incremental is failing
```
$ linz_bde_uploader
-incremental
-config-path /tmp/test_bde_config_0de28ad6ed428bac5dd17788be23554a/linz_bde_uploader.conf -config-extension test_bde_0de28ad6ed428bac5dd17788be23554a
-verbose
-log-level WARN
defined(@array) is deprecated at /usr/share/perl5/Mail/Sender.pm line 318.
        (Maybe you should just omit the defined()?)
defined(@array) is deprecated at /usr/share/perl5/Mail/Sender.pm line 2693.
        (Maybe you should just omit the defined()?)
2016/08/16 22:16:30 ERROR> linz_bde_uploader:224 - Apply Updates Failed: Failed to load level 5 update for crs_action from 20160402183600: Database function applyLevel5Update failed: ERROR:  P0001: Level 5 update of table crs_action from dataset 20160402183600 failed in Applying incremental row updatesError:Error executing template SQL: 
        INSERT INTO bde.crs_action (tin_id,id,sequence,att_type,system_action,act_id_orig,act_tin_id_orig,ste_id,mode,flags,source,audit_id)
        SELECT tin_id,id,sequence,att_type,system_action,act_id_orig,act_tin_id_orig,ste_id,mode,flags,source,audit_id FROM crs_action
        WHERE audit_id IN
          (SELECT id FROM _tmp_inc_actions WHERE action IN ('I','X'))
        
Error: To begin editing bde.crs_action you need to create a revision
LOCATION:  exec_stmt_raise, pl_exec.c:3035 at /usr/share/perl5/LINZ/BdeDatabase.pm line 669.
Error sending mail (-1): The SMTP server linzsmtp was not found at /usr/share/perl5/Log/Dispatch/Email/MailSender.pm line 54.
Error sending mail (-1): The SMTP server linzsmtp was not found at /usr/share/perl5/Log/Dispatch/Email/MailSender.pm line 54.
```

Any ideas ?

**Comment by palmerj** [comment]
@imincik do you have the create and complete revision SQL APIs in the linz_bde_uploader configuration. e.g

```
dataset_load_start_sql <<EOT
SELECT bde_CreateDatasetRevision({{id}});
EOT
```

```
dataset_load_end_sql <<EOT
SELECT bde_CompleteDatasetRevision({{id}});
EOT
```
?

**Comment by palmerj** [comment]
@imincik Any reason why you are using a system created extension: "linz_bde_uploader.conf.test_bde_0de28ad6ed428bac5dd17788be23554a"? Is that for better version management of the config with ansible deployments?

**Comment by imincik** [comment]
@palmerj , thanks for help. You are right, I forgot to add "dataset_load_start_sql" to test config. However, it exists in production config.

"test_bde_0de28ad6ed428bac5dd17788be23554a" "-config-extension" is just for tests. Recently I changed test ID (0de28ad6ed428bac5dd17788be23554a) to unix time which is shorter and better to work with.

For production, I use target database name (linz by default) as "-config-extension".

**Comment by imincik** [comment]
Great, "-config-extension" works now. Thanks for help. Closing.
