### ISSUE TITLE
Move bde_flag_reset.sh functionality into linz_bde_uploader

### ISSUE THREAD

**Issue by ccrook** [linz/linz_bde_uploader#35]
The old production installation prdassgeo01 included a script bde_flag_reset.sh which was used to clear flags when a previous job had failed to run to completion.  I suggest this should be incorporated into the linz_bde_uploader script.  This would involve the run_bde_uploader shell script testing whether a script is running, and if not passing a flag to the linz_bde_uploader perl script to clear the flags.  (This division of labour because the shell script knows what a running job should look like and can test with ps -u and the perl script knows the configuration of the database that needs to be cleared).   

Shell script attached as [bde_flag_reset.sh.txt](https://github.com/linz/linz_bde_uploader/files/421304/bde_flag_reset.sh.txt)

**Comment by palmerj** [comment]
Thanks @ccrook yes agree long needed fix required here.

Also note #25 which is related to this and would in part implement this. Also note that Ivan has started implementing a script in his deployment process https://github.com/linz/ansible-deployment/blob/master/deployment/roles/bde-processor/files/bde_upload, which seems to be a replacement for run_bde_upload, but also deals with first time runs of the uploader on a server. Given this @ccrook and @imincik do you have further thoughts?

**Comment by ccrook** [comment]
Sounds good.  I'll have a look at the perl script soon if no-one else has picked it up before then.   Would be great if @imincik could add the test into the bde_upload script to add a flag to the linz_bde_uploader call if there are no other upload process running, unless there is a better option.

**Comment by imincik** [comment]
I have discovered _bde_flag_reset.sh_ just recently in prdassgeo02. I didn't have a time to think about it.

I would be very happy for any feedback to my bde_upload script. It is not very mature, but if we agree that it is a good idea I will improve it and can add _bde_flag_reset.sh_ functions

**Comment by palmerj** [comment]
resolved in a4ac23b7bb55e8dad19aa3fd77e3734eac377bc0
