### ISSUE TITLE
Remove pre-allocated titles from full Landonline title table

### ISSUE THREAD

**Issue by iharrison** [linz/linz_bde_uploader#42]
Currently pre-allocated titles are included in the full landonline titles table on LDS: https://data.linz.govt.nz/table/2067-landonline-title/

Pending titles are not released so for users of the changesets they get the new pre-allocated title as an insert, then when it moves to pending it comes through as a delete, only to turn up again as an insert once it’s moved past pending status.
The Property Rights team say pre-allocated titles have no value to LDS users.

To filter them out the tmp_excluded_titles table where clause would change to include status='PREA':
CREATE TEMP TABLE tmp_excluded_titles AS
    SELECT
            TTL.title_no
        FROM
            crs_title TTL
        WHERE
            TTL.status = 'PEND' **AND TTL.status = 'PREA'**
    UNION
    SELECT
            title_no
        FROM
            tmp_training_titles;

**Comment by palmerj** [comment]
Moved to https://github.com/linz/linz-lds-bde-schema/issues/15
