### ISSUE TITLE
Landonline 3.15 BDE changes

### ISSUE THREAD

**Issue by billgeo** [linz/linz_bde_uploader#45]
From Dec 11 these files will no longer be part of the BDE:

rna
sad1
rcl1 – crs_road_ctr_line
rns - crs_road_name_asc
xrna - crs_road_name
xsad - crs_street_address

**Comment by palmerj** [comment]
Looks like we also need to swtich from the cos to xcos file as well as per https://github.com/linz/linz_bde_uploader_private/commit/d45f0f83d60def2b50d913cd1cd60af3c46e603c
