### ISSUE TITLE
Can't locate inc/MyBuilder.pm 

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#48]
Following manual install instructions in the README.md I hit a readblock on `perl Build.PL` which returns an error:
```
Can't locate inc/MyBuilder.pm in @INC (you may need to install the inc::MyBuilder module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at Build.PL line 18.
BEGIN failed--compilation aborted at Build.PL line 18.
```
This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi
on an Ubuntu 17.04 system

**Comment by strk** [comment]
The problem seems to be that `@INC` does not contain `.` (the current directory)

**Comment by palmerj** [comment]
See https://lists.debian.org/debian-devel-announce/2016/08/msg00013.html. We have only tested with Perl5 version 22 and below

**Comment by palmerj** [comment]
Are you not using Ubuntu 16.04 in your Ansible testing?

**Comment by strk** [comment]
The Vagrant machine in bde-processing-deployment is an Ubuntu 14.04, which indeed uses Perl version 5.18.2 (so is unaffected). This ticket is specifically to adapt the build to a newer perl version. I'll continue using the Vagrant machine to make this a non-blocker.

**Comment by strk** [comment]
I confirm the Perl version in Vagrant machine (5.18.2) can run the build command just fine.

**Comment by strk** [comment]
For the record: Travis is now running `perl Build.PL` (is invoked by `./configure`) with perl versions from 5.12 to 5.24 and has no problem with that, so the problem must be in my specific setup of perl or something (Ubuntu 17.04 here).

Someone mentioned it'll be a problem with Perl 5.26 but debian perl package makes it a problem starting with perl 5.24 (which is what I have). Maybe travis uses a different package.

PR #73 is to fix that (even if Travis cannot reproduce it, I'll have this fixed for myself anyway)

**Comment by strk** [comment]
Perfect, travis reproduced this: https://travis-ci.org/linz/linz_bde_uploader/builds/244978294?utm_source=github_status&utm_medium=notification
