### ISSUE TITLE
Document (or drop) dependency on territorial admin boundary data

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#51]
As reported in https://github.com/linz/bde-processor-deployment/issues/17#issuecomment-302995691 there's a dependency of `linz_bde_uploader` on the presence of a `territorial_authority` table used by the  [LDS.LDS_MaintainSimplifiedElectoralLayers](https://github.com/linz/linz-lds-bde-schema/blob/master/sql/04-lds_layer_functions.sql#L3296) PL/Pgsql function.

This ticket is to document this dependency and how to deal with it in the README.md file, together with info about obtaining that data.

Alternative, @palmerj mentioned the dependency could be also dropped.
I dunno if this relates with #39 in any way

**Comment by palmerj** [comment]
Actually wondering if this ticket should be in linz-lds-bde-schema repo

**Comment by strk** [comment]
Good question. It would sound appropriate for the table schema and the table populating script maybe to be in that `linz-lds-bde-schema`

**Comment by strk** [comment]
So, ticket moved to https://github.com/linz/linz-lds-bde-schema/issues/4
