### ISSUE TITLE
duplicated output lines

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#59]
The output from `linz_bde_uploader` is very verbose, and duplication contributes to the difficulty of reading it. Here's an extract:
```
$ sudo -u bde linz_bde_uploader -dry-run -incremental -config-path /etc/linz-bde-uploader/linz_bde_uploader.conf -config-extension dev-linz-bde-uploader  -log-level INFO -remove-zombie -listing /tmp/bde.log -before 20150701  -skip-postupload-tasks 2>&1 > /dev/null | head -10

2017/05/25 02:58:12 Cannot load incremental updates to crs_action as there is no previous upload
2017/05/25 02:58:12 ERROR> BdeUpload.pm:677 - Cannot load incremental updates to crs_action as there is no previous upload
2017/05/25 02:58:12 Cannot load incremental updates to crs_action_type as there is no previous upload
2017/05/25 02:58:12 ERROR> BdeUpload.pm:677 - Cannot load incremental updates to crs_action_type as there is no previous upload
2017/05/25 02:58:12 Cannot load incremental updates to crs_adj_obs_change as there is no previous upload
2017/05/25 02:58:12 ERROR> BdeUpload.pm:677 - Cannot load incremental updates to crs_adj_obs_change as there is no previous upload
2017/05/25 02:58:12 Cannot load incremental updates to crs_adj_user_coef as there is no previous upload
2017/05/25 02:58:12 ERROR> BdeUpload.pm:677 - Cannot load incremental updates to crs_adj_user_coef as there is no previous upload
2017/05/25 02:58:12 Cannot load incremental updates to crs_adjust_coef as there is no previous upload
2017/05/25 02:58:12 ERROR> BdeUpload.pm:677 - Cannot load incremental updates to crs_adjust_coef as there is no previous upload
```

Each line is first printed without prefix, and then printed with `ERROR> BdeUpload.pm:677 - ` prefix.
Is there any way to hush one of them ?

**Comment by palmerj** [comment]
@strk I think more investigation is required, but from I see I would suggest reviewing what's going on at in the log initialisation code to ensure multiple log appenders are not being incorrectly created. See https://github.com/linz/linz_bde_uploader/blob/master/lib/LINZ/BdeUpload.pm#L677. The think the issue is you are using both the dry run and listing CL options. So that situation needs to be correctly fixed.

Also I would say at some point another ticket should be raised to review all log levels to ensure we log what is required. e.g some message at INFO might only need to be DEBUG, or some ERROR messages that should be FATAL.

**Comment by strk** [comment]
For the record, this issue would be fixed by merging #60, pending a review from you @palmerj

**Comment by strk** [comment]
Now that a testsuite in in place I've tried reproducing the problem with a test, but more problems are coming out. In particular, errors like `unexistent database` are not printed at all, in master branch. Neither to logfile nor to stdout or stderr..

**Comment by strk** [comment]
Sorry, taking it back. Those errors are printed to `stderr` instead of to logfile in master, and nowhere in the branch of #60 -- What is the expected behavior with reguard to logs when -dry-run is used ?

**Comment by strk** [comment]
So while the code shows that the duplication is by design:
```
    if($verbose || $dry_run)                                                    
    {                                                                           
        my $stdout_appender = Log::Log4perl::Appender->new(                     
            "Log::Log4perl::Appender::Screen",                                  
            name      => "verbose_screen_log",                                  
        );                                                                      
        $stdout_appender->layout($layout);                                      
        $logger->add_appender($stdout_appender);                                
    }            
```

The test shows that the same error gets twice on stderr. 
Documentation says that for `verbose` the message should go on stdout, btw.

**Comment by strk** [comment]
New PR avoids to add a new appender for -dry-run (which is already configured with a simple Screen appender, skipping the logging configuration altogheter)

**Comment by imincik** [comment]
I like idea of printing all messages to screen in `-dry-run`
