### ISSUE TITLE
Invalid linz_bde_uploader invocation return success status and writes to stdout

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#66]
When calling `linz_bde_uploader` with no arguments (I'm putting this under automated testing) it prints a usage string on `stdout` and returns with a success (0) exit code.

It would make more sense to print to `stderr` instead (but @palmerj or @imincik might have a reason to avoid that) and most importantly to return non-success (non-0) exit code.

**Comment by imincik** [comment]
+1 from me for printing to `stderr`. Thanks
