### ISSUE TITLE
`Cannot open configuration file` printed on stdout

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#68]
Invoking `linz_bde_uploader` script with just a `-full` switch and nonexistent configuration file results in a message being printed on stdout:
```
Cannot open configuration file ...
```

It should be printed on stderr instead.

The message originates in [linz_utils_perl](https://github.com/linz/linz_utils_perl), so I'm not sure it can be fixed w/out changing that module.

**Comment by strk** [comment]
This will be fixed by merging e91cd88 from #67

**Comment by imincik** [comment]
Thanks, this was annoying me too.
