### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by dkourilov** [linz/linz_bde_uploader#7]
Documentation available at https://github.com/linz/linz_bde_uploader/blob/master/README has few inconsistencies.

First, it refers that the application was under Ubuntu 10.4 (Lucid), but prerequisites list PostgreSQL 9.0 as a required components. There is no official backport of PostgreSQL 9.X for Ubuntu Lucid, it is available only on Ubuntu Precise. 

Next, "createdb -O postgres -E UTF8" command creates database with POSIX collation, rather than en_NZ.UTF-8, which is essential for sorting Maori place names.

Also, it might be handy to provide linz_bde_uploader as a debian package, there is a free package building service available at https://launchpad.net/, also it has very tight integration with Ubuntu Linux:
```bash
#repositories from lauchpad.net can be added very straighforward for Ubuntu user
$ add-apt-repository ppa:linz/bde
$ apt-get install linz_bde_uploader
```

Currently, until PPA or other package hosting service is not used, it is suggested to list prerequisities in form of debian packages:
```bash
apt-get install libfile-which-perl libdbd-pg-perl \
                     libdate-calc-perl liblog-dispatch-perl \
                     liblog-log4perl-perl liblog-dispatch-filerotate-perl
```

**Comment by palmerj** [comment]
Closing. Will produce new packaging process in version 2.0
