### ISSUE TITLE
Be tolerant about missing SQL hook directives

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#78]
Writing tests for the configuration of uploader I'm finding that the script is very picky about presence of many directives which may safely get good defaults. In particular all the SQL hooks (dataset_load_end_sql, db_upload_complete_sql, ...) could all be assumed to be empty.

Is there any reason to be so picky @palmerj, @imincik ?

**Comment by imincik** [comment]
+1 from me to have a good defaults.
