### ISSUE TITLE
Byte Order Mark in sql files

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#81]
I found that sql/* files have [byte order markers](https://en.wikipedia.org/wiki/Byte_order_mark), which confuse code like:
```
  cat sql/* | psql
```

With errors like:
```
syntax error at or near "<U+FEFF>"
```

Is there any reason to keep them there ? (it's usually some Windows thing..)

**Comment by strk** [comment]
NOTE: editorconfig can express charset to be utf8 (with no bom), see `charset` in http://editorconfig.org/

**Comment by strk** [comment]
See also [this article](https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom/2223926#2223926) about BOM being discouraged

**Comment by imincik** [comment]
For me it looks like some garbage .

**Comment by strk** [comment]
So do you agree that I remove it and add a charset section in `.editorconfig` to prevent it being added again (by editors *supporting* editorconfig..) ?

**Comment by imincik** [comment]
> So do you agree that I remove it and add a charset section in .editorconfig to prevent it being added again (by editors supporting editorconfig..) ?

@strk , yes please.
