### ISSUE TITLE
Error: extra data after last expected column

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_uploader#90]
I'm very close to complete the first successful upload but I'm stuck here:
```
# ERROR - Apply Updates Failed: Failed to load level 0 update for crs_parcel_bndry from 20170622170629: Database function uploadDataToTempTable failed: ERROR:  P0001: Error encountered loading file /tmp/tmp_bde_upload_2/test_file_20170622170629_1.unl into table crs_parcel_bndry. SQL: COPY bde_upload_2.crs_parcel_bndry(pri_id, sequence, lin_id, reversed, audit_id) FROM '/tmp/tmp_bde_upload_2/test_file_20170622170629_1.unl' WITH DELIMITER '|' NULL AS ''. Error: extra data after last expected column
# CONTEXT:  PL/pgSQL function bde_uploaddatatotemptable(integer,name,text,text) line 31 at RAISE
# LOCATION:  exec_stmt_raise, pl_exec.c:3165 at /usr/src/linz/linz_bde_uploader/blib/script/../lib/LINZ/BdeDatabase.pm line 669.
```

The file does indeed have an extra delimiter (for 5 fields):
```
4457326|1|29694591|Y|80401148|
4457326|2|29694578|Y|80401149|
4457326|3|11960041|Y|80401150|
```

This pretty much matches the `.crs` ending:
```
{CRS-DATA}                                                                      
4457326|1|29694591|Y|80401148|
4457326|2|29694578|Y|80401149|
4457326|3|11960041|Y|80401150|
```

Removing the `|` ending from the `.crs` file complains about `Incorrect number of field`, so cannot be the fix (the `.crs` file does have 5 columns).

This happens with PostgreSQL 9.6.2, in case it matters.

Does it ring any bell @palmerj @imincik  ?

**Comment by strk** [comment]
Same error can be seen on Travis, which uses PostgreSQL 9.4:
https://travis-ci.org/linz/linz_bde_uploader/jobs/245862774#L648

**Comment by imincik** [comment]
> Does it ring any bell @palmerj @imincik ?

Sorry, no idea.

**Comment by strk** [comment]
I suspect this has to do with `output_fields` configuration and handling of `linz-bde-perl`, should test the specific call being made, with something like https://github.com/linz/linz_bde_perl/blob/76f8b21b0ccd51e7cdeacc3871a9b079dd5ca891/t/BdeFile.t#L113-L117

**Comment by strk** [comment]
This command:

```
bde_copy -o pri_id:sequence:lin_id:reversed:audit_id \
   test_file.crs \
   test_file.unl \
   test_file.log
```

Results in a test_file.unl with this content:
```
4457326|1|29694591|Y|80401148|
4457326|2|29694578|Y|80401149|
4457326|3|11960041|Y|80401150|
```

This clearly cannot be used as a `COPY FROM` source for a target table with 5 fields (as requested by the `-o` switch because it has 5 `|` separators and thus 6 fields.

I think this is a bug in `bde_copy`

**Comment by strk** [comment]
I filed this for `bde_copy`: https://github.com/linz/linz_bde_copy/issues/25
But could as well be a bug in `lib_bde_perl`...

**Comment by strk** [comment]
So it turns out that the problem with additional pipe is due to `bde_copy` using by default a system-wide configuration file that explicitly requests a `line_ending` which contains a pipe, and `LINZ::BdeUpload` method `BuildTempFile` makes no effort to check that or change it to what's needed for `COPY FROM` to work fine.

Instead, `bde_copy` is passed a custom configuration file *if* such file is specified in the configuration file of `linz_bde_uploader` itself, using the `bde_copy_configuration` directive.

The example `linz_bde_uploader` configuration (which is *not* read by default) does contain a working such configuration. From conf/linz_bde_uploader.conf:
```
# Configuration of bde_copy

bde_copy_configuration << end_bde_copy_configuration


# Field and line terminators
# Characters are either \xHH, \x or a character.  Use \x20 for a space character
# Multi-character terminators are valid

field_separator |
line_terminator \x0A

...
```


I think for the sake of this bug the script should basically make sure that `line_terminator` is correctly set, when calling `bde_copy`. Ideally `bde_copy` should accept command-line overrides of configuration parameters, which would make things much simpler.

**Comment by strk** [comment]
Wonders, `bde_copy` accepts a `-c` switch that can be *both* a filename *or* a string with newlines which would be interpreted as the contents of such configuration. As odd as it looks, it would let us override things, but we need to ensure there's a newline in the value ...

**Comment by strk** [comment]
Sorry it is not `bde_copy` doing this weird thing with interpretation of `-c` switch, but `LINZ::Bde` method `copy`, using the value of the `config` member of the `options` argument (3rd argument).
If the value contains newlines, then it is considered full configuration, and a temporary file is created for the sake of passing it via `-c` to `bde_copy`:

```
sub copy                                                                        
{                                                                               
    my($self,$outputfile,@options) = @_;                                        
                                                                                
    my $exe = _bdecopy();                                                       
    my $opts = ref($options[0]) ? $options[0] : {@options};                     
    my @copyopts;                                                               
    my $cfgtmp;                                                                 
    my $cfg = $opts->{config};                                                  
    if( $cfg =~ /\n/)                                                           
    {                                                                           
        use File::Temp;                                                         
        my $htmp;                                                               
        ($htmp,$cfgtmp) = File::Temp::tempfile();                               
        print $htmp $cfg;                                                       
        CORE::close($htmp);                                                     
        $cfg = $cfgtmp;                                                         
    }                                                                           
    push(@copyopts,'-c',$cfg) if $cfg;     
```
